#!/bin/sh

export version=$1
export branch=$2
export dir=tiki_$version
export db=tiki_$version

export MYSQLCONNSTR_Tiki="Database=$db;Data Source=localhost;User Id=$db;Password=$db"
export TIKI_INI_FILE="/etc/tiki.ini"
export TIKI_INI_IDENTIFIER=$db

export PS1="\033]0;Tiki ${version}\007\e[1;94mTiki ${version} \e[1;97m\$\e[0m "
echo -ne "\033]0;Activating Tiki ${version}...\007"

if [ ! -d $dir ]; then
	if [ -n "$branch" ]; then
		svn checkout https://svn.code.sf.net/p/tikiwiki/code/$branch $dir
		cd $dir
		bash doc/devtools/svnup.sh
		php console.php database:install
	else
		echo "Tiki $version not initialized. Provide the branch to checkout."
	fi
else
	cd $dir
	bash doc/devtools/svnup.sh
fi
